name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kubepractice
    - name: tag image
      run: docker tag kubepractice gcr.io/kubepractice-04192021/kubepractice
    - name: push image
      run: docker push gcr.io/kubepractice-04192021/kubepractice
      with:
        project_id: kubepractice-04192021
        service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}